skip = ["encoder.layer0.bn1.num_batches_tracked", "encoder.layer1.0.bn1.num_batches_tracked",
        "encoder.layer1.0.bn2.num_batches_tracked", "encoder.layer1.0.bn3.num_batches_tracked",
        "encoder.layer1.0.downsample.1.num_batches_tracked", "encoder.layer1.1.bn1.num_batches_tracked",
        "encoder.layer1.1.bn2.num_batches_tracked", "encoder.layer1.1.bn3.num_batches_tracked",
        "encoder.layer1.2.bn1.num_batches_tracked", "encoder.layer1.2.bn2.num_batches_tracked",
        "encoder.layer1.2.bn3.num_batches_tracked", "encoder.layer2.0.bn1.num_batches_tracked",
        "encoder.layer2.0.bn2.num_batches_tracked", "encoder.layer2.0.bn3.num_batches_tracked",
        "encoder.layer2.0.downsample.1.num_batches_tracked", "encoder.layer2.1.bn1.num_batches_tracked",
        "encoder.layer2.1.bn2.num_batches_tracked", "encoder.layer2.1.bn3.num_batches_tracked",
        "encoder.layer2.2.bn1.num_batches_tracked", "encoder.layer2.2.bn2.num_batches_tracked",
        "encoder.layer2.2.bn3.num_batches_tracked", "encoder.layer2.3.bn1.num_batches_tracked",
        "encoder.layer2.3.bn2.num_batches_tracked", "encoder.layer2.3.bn3.num_batches_tracked",
        "encoder.layer3.0.bn1.num_batches_tracked", "encoder.layer3.0.bn2.num_batches_tracked",
        "encoder.layer3.0.bn3.num_batches_tracked", "encoder.layer3.0.downsample.1.num_batches_tracked",
        "encoder.layer3.1.bn1.num_batches_tracked", "encoder.layer3.1.bn2.num_batches_tracked",
        "encoder.layer3.1.bn3.num_batches_tracked", "encoder.layer3.2.bn1.num_batches_tracked",
        "encoder.layer3.2.bn2.num_batches_tracked", "encoder.layer3.2.bn3.num_batches_tracked",
        "encoder.layer3.3.bn1.num_batches_tracked", "encoder.layer3.3.bn2.num_batches_tracked",
        "encoder.layer3.3.bn3.num_batches_tracked", "encoder.layer3.4.bn1.num_batches_tracked",
        "encoder.layer3.4.bn2.num_batches_tracked", "encoder.layer3.4.bn3.num_batches_tracked",
        "encoder.layer3.5.bn1.num_batches_tracked", "encoder.layer3.5.bn2.num_batches_tracked",
        "encoder.layer3.5.bn3.num_batches_tracked", "encoder.layer4.0.bn1.num_batches_tracked",
        "encoder.layer4.0.bn2.num_batches_tracked", "encoder.layer4.0.bn3.num_batches_tracked",
        "encoder.layer4.0.downsample.1.num_batches_tracked", "encoder.layer4.1.bn1.num_batches_tracked",
        "encoder.layer4.1.bn2.num_batches_tracked", "encoder.layer4.1.bn3.num_batches_tracked",
        "encoder.layer4.2.bn1.num_batches_tracked", "encoder.layer4.2.bn2.num_batches_tracked",
        "encoder.layer4.2.bn3.num_batches_tracked", "encoder1.bn1.num_batches_tracked",
        "encoder2.0.bn1.num_batches_tracked", "encoder2.0.bn2.num_batches_tracked",
        "encoder2.0.bn3.num_batches_tracked", "encoder2.0.downsample.1.num_batches_tracked",
        "encoder2.1.bn1.num_batches_tracked", "encoder2.1.bn2.num_batches_tracked",
        "encoder2.1.bn3.num_batches_tracked", "encoder2.2.bn1.num_batches_tracked",
        "encoder2.2.bn2.num_batches_tracked", "encoder2.2.bn3.num_batches_tracked",
        "encoder3.0.bn1.num_batches_tracked", "encoder3.0.bn2.num_batches_tracked",
        "encoder3.0.bn3.num_batches_tracked", "encoder3.0.downsample.1.num_batches_tracked",
        "encoder3.1.bn1.num_batches_tracked", "encoder3.1.bn2.num_batches_tracked",
        "encoder3.1.bn3.num_batches_tracked", "encoder3.2.bn1.num_batches_tracked",
        "encoder3.2.bn2.num_batches_tracked", "encoder3.2.bn3.num_batches_tracked",
        "encoder3.3.bn1.num_batches_tracked", "encoder3.3.bn2.num_batches_tracked",
        "encoder3.3.bn3.num_batches_tracked", "encoder4.0.bn1.num_batches_tracked",
        "encoder4.0.bn2.num_batches_tracked", "encoder4.0.bn3.num_batches_tracked",
        "encoder4.0.downsample.1.num_batches_tracked", "encoder4.1.bn1.num_batches_tracked",
        "encoder4.1.bn2.num_batches_tracked", "encoder4.1.bn3.num_batches_tracked",
        "encoder4.2.bn1.num_batches_tracked", "encoder4.2.bn2.num_batches_tracked",
        "encoder4.2.bn3.num_batches_tracked", "encoder4.3.bn1.num_batches_tracked",
        "encoder4.3.bn2.num_batches_tracked", "encoder4.3.bn3.num_batches_tracked",
        "encoder4.4.bn1.num_batches_tracked", "encoder4.4.bn2.num_batches_tracked",
        "encoder4.4.bn3.num_batches_tracked", "encoder4.5.bn1.num_batches_tracked",
        "encoder4.5.bn2.num_batches_tracked", "encoder4.5.bn3.num_batches_tracked",
        "encoder5.0.bn1.num_batches_tracked", "encoder5.0.bn2.num_batches_tracked",
        "encoder5.0.bn3.num_batches_tracked", "encoder5.0.downsample.1.num_batches_tracked",
        "encoder5.1.bn1.num_batches_tracked", "encoder5.1.bn2.num_batches_tracked",
        "encoder5.1.bn3.num_batches_tracked", "encoder5.2.bn1.num_batches_tracked",
        "encoder5.2.bn2.num_batches_tracked", "encoder5.2.bn3.num_batches_tracked",
        "center.0.bn.num_batches_tracked", "center.2.bn.num_batches_tracked",
        "decoder5.conv1.bn.num_batches_tracked", "decoder5.conv2.bn.num_batches_tracked",
        "decoder5.context.0.context.1.num_batches_tracked",
        "decoder5.context.0.context.3.stages.0.f_key.1.num_batches_tracked",
        "decoder5.context.0.context.3.stages.0.f_query.1.num_batches_tracked",
        "decoder5.context.0.context.3.conv_bn_dropout.1.num_batches_tracked",
        "decoder5.context.0.conv2.1.num_batches_tracked", "decoder5.context.0.conv3.1.num_batches_tracked",
        "decoder5.context.0.conv4.1.num_batches_tracked", "decoder5.context.0.conv5.1.num_batches_tracked",
        "decoder5.context.0.conv_bn_dropout.1.num_batches_tracked", "decoder4.conv1.bn.num_batches_tracked",
        "decoder4.conv2.bn.num_batches_tracked", "decoder4.context.0.context.1.num_batches_tracked",
        "decoder4.context.0.context.3.stages.0.f_key.1.num_batches_tracked",
        "decoder4.context.0.context.3.stages.0.f_query.1.num_batches_tracked",
        "decoder4.context.0.context.3.conv_bn_dropout.1.num_batches_tracked",
        "decoder4.context.0.conv2.1.num_batches_tracked", "decoder4.context.0.conv3.1.num_batches_tracked",
        "decoder4.context.0.conv4.1.num_batches_tracked", "decoder4.context.0.conv5.1.num_batches_tracked",
        "decoder4.context.0.conv_bn_dropout.1.num_batches_tracked", "decoder3.conv1.bn.num_batches_tracked",
        "decoder3.conv2.bn.num_batches_tracked", "decoder3.context.0.context.1.num_batches_tracked",
        "decoder3.context.0.context.3.stages.0.f_key.1.num_batches_tracked",
        "decoder3.context.0.context.3.stages.0.f_query.1.num_batches_tracked",
        "decoder3.context.0.context.3.conv_bn_dropout.1.num_batches_tracked",
        "decoder3.context.0.conv2.1.num_batches_tracked", "decoder3.context.0.conv3.1.num_batches_tracked",
        "decoder3.context.0.conv4.1.num_batches_tracked", "decoder3.context.0.conv5.1.num_batches_tracked",
        "decoder3.context.0.conv_bn_dropout.1.num_batches_tracked", "decoder2.conv1.bn.num_batches_tracked",
        "decoder2.conv2.bn.num_batches_tracked", "decoder2.context.0.context.1.num_batches_tracked",
        "decoder2.context.0.context.3.stages.0.f_key.1.num_batches_tracked",
        "decoder2.context.0.context.3.stages.0.f_query.1.num_batches_tracked",
        "decoder2.context.0.context.3.conv_bn_dropout.1.num_batches_tracked",
        "decoder2.context.0.conv2.1.num_batches_tracked", "decoder2.context.0.conv3.1.num_batches_tracked",
        "decoder2.context.0.conv4.1.num_batches_tracked", "decoder2.context.0.conv5.1.num_batches_tracked",
        "decoder2.context.0.conv_bn_dropout.1.num_batches_tracked", "decoder1.conv1.bn.num_batches_tracked",
        "decoder1.conv2.bn.num_batches_tracked", "decoder1.context.0.context.1.num_batches_tracked",
        "decoder1.context.0.context.3.stages.0.f_key.1.num_batches_tracked",
        "decoder1.context.0.context.3.stages.0.f_query.1.num_batches_tracked",
        "decoder1.context.0.context.3.conv_bn_dropout.1.num_batches_tracked",
        "decoder1.context.0.conv2.1.num_batches_tracked", "decoder1.context.0.conv3.1.num_batches_tracked",
        "decoder1.context.0.conv4.1.num_batches_tracked", "decoder1.context.0.conv5.1.num_batches_tracked",
        "decoder1.context.0.conv_bn_dropout.1.num_batches_tracked"]